<a href="https://colab.research.google.com/github/vlysicc/cheatcodesss/blob/main/LecQuiz3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:

messy_data = {
    'patient_name': ['Dela Cruz', 'Santos', 'Reyes', 'bautista', 'GARCIA ', ' Mendoza', 'Torres', 'Ramos',
        'Aquino', 'Fernandez', 'delaCruz', 'Santos', 'Villanueva', 'Domingo', 'Castro',
        None, 'Reyes', 'Navarro', None, 'Pascual', 'Torres', 'Aquino', 'Bautista', 'Cruz', 'Mercado'],

    'sex': ['M','F','Male','female','M','F','m','F','M','Female','F','M','F','M','F',
        'M','F','M','F','M','F','M','F','M','F'],

    'barangay': ['San Roque','Bagumbayan','san roque','Poblacion','Bagumbayan ','San Jose',
        'Poblacion','Sto. Nino','San Roque','Bagumbayan','Poblacion','San Jose',
        'Sto Nino','San Roque','Bagumbayan','Poblacion','San Roque','San Jose',
        'Bagumbayan','Poblacion','Sto. Nino','San Roque','San Jose','Bagumbayan','Poblacion'],

    'visit_date': ['2026-01-05','01/06/2026','2026-1-7','2026-01-08','08-01-2026','2026-01-09',
        '2026-01-09','2026/01/10','2026-01-11','01-12-2026','2026-01-13','2026-01-13',
        '2026-01-14','2026-01-15',None,'2026-01-16','2026-01-17','2026-01-18',
        '2026-01-19','2026-01-20','2026-01-20','2026-01-21','2026-01-22','2026-01-23','2026-01-24'],

    'age': [34, 5, 150, 27, np.nan, 62, 41, 8, np.nan, 29, 34, 5, 71, 45, 19, -3, 55, np.nan, 22, 38, 41, np.nan, 60, 34, 47],

    'weight_kg': ['65kg','18.5','58 kg','70.2','80','45.0kg','150','20','55.5','62','65kg','18.5',
        '68','75',np.nan,'-40','90kg','52','30','77','68','58','95','65kg','61'],

    'height_cm': [165, 110, 170, np.nan, 175, 150, 168, 128, 160, 172, 165, 110, 155, 180, 140,
        169, 158, np.nan, 132, 162, 168, 173, 5.9, 165, 159],

    'bp_systolic': ['120','95','210','130','118','160','122','100','300','125','120','95','140',
        '135','108','119','150','127','98','131','122','128','145','120','133'],

    'temperature_c': [36.5, 37.0, 39.8, 36.7, 36.6, 38.2, 36.9, 36.8, 42.5, 36.5, 36.5, 37.0,
        37.1, 36.4, 36.9, 36.6, 40.1, 36.7, 36.8, 36.9, 36.5, 37.2, 39.0, 36.5, 36.6],

    'diagnosis': ['Hypertension','Common Cold','hypertension','Diabetes','COMMON COLD','Flu',
        'Hypertension ','Asthma','Diabetes Type 2','common cold','Hypertension','Common Cold',
        'Migraine','Flu','UTI','Hypertension','diabetes','Asthma','Common Cold','Flu',
        'Hypertension','Diabetes','Migrain','Hypertension','UTI'],

    'follow_up_needed': ['Yes','No','yes','NO','Y','N','Yes','No','yes','No','Yes','No','No',
        'Yes','No','Yes','yes','No','N','Yes','Yes','No','Y','Yes','No'],

   'senior_citizen': [0,0,1,0,1,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0]
}

df = pd.DataFrame(messy_data)

print("Original Dataset:")
display(df)

Original Dataset:

,patient_name,sex,barangay,visit_date,age,weight_kg,height_cm,bp_systolic,temperature_c,diagnosis,follow_up_needed,senior_citizen
0,Dela Cruz,M,San Roque,2026-01-05,34.0,65kg,165.0,120,36.5,Hypertension,Yes,0
1,Santos,F,Bagumbayan,01/06/2026,5.0,18.5,110.0,95,37.0,Common Cold,No,0
2,Reyes,Male,san roque,2026-1-7,150.0,58 kg,170.0,210,39.8,hypertension,yes,1
3,bautista,female,Poblacion,2026-01-08,27.0,70.2,NaN,130,36.7,Diabetes,NO,0
4,GARCIA,M,Bagumbayan,08-01-2026,NaN,80,175.0,118,36.6,COMMON COLD,Y,1
5,Mendoza,F,San Jose,2026-01-09,62.0,45.0kg,150.0,160,38.2,Flu,N,1
6,Torres,m,Poblacion,2026-01-09,41.0,150,168.0,122,36.9,Hypertension,Yes,0
7,Ramos,F,Sto. Nino,2026/01/10,8.0,20,128.0,100,36.8,Asthma,No,0
8,Aquino,M,San Roque,2026-01-11,NaN,55.5,160.0,300,42.5,Diabetes Type 2,yes,0
9,Fernandez,Female,Bagumbayan,01-12-2026,29.0,62,172.0,125,36.5,common cold,No,0
10,delaCruz,F,Poblacion,2026-01-13,34.0,65kg,165.0,120,36.5,Hypertension,Yes,0
11,Santos,M,San Jose,2026-01-13,5.0,18.5,110.0,95,37.0,Common Cold,No,0
12,Villanueva,F,Sto Nino,2026-01-14,71.0,68,155.0,140,37.1,Migraine,No,1
13,Domingo,M,San Roque,2026-01-15,45.0,75,180.0,135,36.4,Flu,Yes,0
14,Castro,F,Bagumbayan,None,19.0,NaN,140.0,108,36.9,UTI,No,0
15,None,M,Poblacion,2026-01-16,-3.0,-40,169.0,119,36.6,Hypertension,Yes,0
16,Reyes,F,San Roque,2026-01-17,55.0,90kg,158.0,150,40.1,diabetes,yes,1
17,Navarro,M,San Jose,2026-01-18,NaN,52,NaN,127,36.7,Asthma,No,0
18,None,F,Bagumbayan,2026-01-19,22.0,30,132.0,98,36.8,Common Cold,N,0
19,Pascual,M,Poblacion,2026-01-20,38.0,77,162.0,131,36.9,Flu,Yes,0
20,Torres,F,Sto. Nino,2026-01-20,41.0,68,168.0,122,36.5,Hypertension,Yes,0
21,Aquino,M,San Roque,2026-01-21,NaN,58,173.0,128,37.2,Diabetes,No,1
22,Bautista,F,San Jose,2026-01-22,60.0,95,5.9,145,39.0,Migrain,Y,1
23,Cruz,M,Bagumbayan,2026-01-23,34.0,65kg,165.0,120,36.5,Hypertension,Yes,0
24,Mercado,F,Poblacion,2026-01-24,47.0,61,159.0,133,36.6,UTI,No,0

STEP 1

In [ ]:

print("Missing Values:")
print(df.isnull().sum())

Missing Values:
patient_name        2
sex                 0
barangay            0
visit_date          1
age                 4
weight_kg           1
height_cm           2
bp_systolic         0
temperature_c       0
diagnosis           0
follow_up_needed    0
senior_citizen      0
dtype: int64

STEP 2

In [ ]:

display(df[df['patient_name'].isna()])

,patient_name,sex,barangay,visit_date,age,weight_kg,height_cm,bp_systolic,temperature_c,diagnosis,follow_up_needed,senior_citizen
15,None,M,Poblacion,2026-01-16,-3.0,-40,169.0,119,36.6,Hypertension,Yes,0
18,None,F,Bagumbayan,2026-01-19,22.0,30,132.0,98,36.8,Common Cold,N,0

STEP 3

In [ ]:

print("Before cleaning:", df['barangay'].nunique())

df['barangay'] = df['barangay'].str.strip().str.title()

print("After cleaning:", df['barangay'].nunique())
print(df['barangay'].unique())

Before cleaning: 8
After cleaning: 6
['San Roque' 'Bagumbayan' 'Poblacion' 'San Jose' 'Sto. Nino' 'Sto Nino']

STEP 4

In [ ]:

df['visit_date'] = pd.to_datetime(df['visit_date'], errors='coerce')

df = df.sort_values('visit_date')

display(df[['patient_name', 'visit_date']])

print("\nVisits per day:")
print(df['visit_date'].value_counts().sort_index())

   patient_name visit_date
0     Dela Cruz 2026-01-05
2         Reyes 2026-01-07
3      bautista 2026-01-08
5       Mendoza 2026-01-09
6        Torres 2026-01-09
8        Aquino 2026-01-11
10     delaCruz 2026-01-13
11       Santos 2026-01-13
12   Villanueva 2026-01-14
13      Domingo 2026-01-15
15         None 2026-01-16
16        Reyes 2026-01-17
17      Navarro 2026-01-18
18         None 2026-01-19
19      Pascual 2026-01-20
20       Torres 2026-01-20
21       Aquino 2026-01-21
22     Bautista 2026-01-22
23         Cruz 2026-01-23
24      Mercado 2026-01-24
1        Santos        NaT
4       GARCIA         NaT
7         Ramos        NaT
9     Fernandez        NaT
14       Castro        NaT

Visits per day:
visit_date
2026-01-05    1
2026-01-07    1
2026-01-08    1
2026-01-09    2
2026-01-11    1
2026-01-13    2
2026-01-14    1
2026-01-15    1
2026-01-16    1
2026-01-17    1
2026-01-18    1
2026-01-19    1
2026-01-20    2
2026-01-21    1
2026-01-22    1
2026-01-23    1
2026-01-24    1
Name: count, dtype: int64

STEP 5

In [ ]:

display(
    df[df['patient_name'].duplicated(keep=False)]
    [['patient_name', 'age', 'barangay', 'visit_date']]
)

   patient_name    age    barangay visit_date
2         Reyes  150.0   San Roque 2026-01-07
6        Torres   41.0   Poblacion 2026-01-09
8        Aquino    NaN   San Roque 2026-01-11
11       Santos    5.0    San Jose 2026-01-13
15         None   -3.0   Poblacion 2026-01-16
16        Reyes   55.0   San Roque 2026-01-17
18         None   22.0  Bagumbayan 2026-01-19
20       Torres   41.0   Sto. Nino 2026-01-20
21       Aquino    NaN   San Roque 2026-01-21
1        Santos    5.0  Bagumbayan        NaT

STEP 6

In [ ]:

df['patient_name'] = df['patient_name'].str.strip().str.title()

df['sex'] = df['sex'].str.strip().str.lower()
df['sex'] = df['sex'].replace({
    'm': 'Male',
    'male': 'Male',
    'f': 'Female',
    'female': 'Female'
})

df['diagnosis'] = df['diagnosis'].str.strip().str.title()
df['diagnosis'] = df['diagnosis'].replace({
    'Migrain': 'Migraine'
})

df['follow_up_needed'] = df['follow_up_needed'].str.strip().str.lower()
df['follow_up_needed'] = df['follow_up_needed'].replace({
    'yes': 'Yes',
    'y': 'Yes',
    'no': 'No',
    'n': 'No'
})


df.loc[(df['age'] < 0) | (df['age'] > 120), 'age'] = np.nan

df_clean = df.dropna(subset=['patient_name']).copy()

display(df_clean)

print("Total valid patients:", len(df_clean))
print("Average age:", round(df_clean['age'].mean(), 2))
print("Most common diagnosis:", df_clean['diagnosis'].mode()[0])

follow_up = (df_clean['follow_up_needed'] == 'Yes').mean() * 100
print("Percentage needing follow-up:", round(follow_up, 2), "%")

,patient_name,sex,barangay,visit_date,age,weight_kg,height_cm,bp_systolic,temperature_c,diagnosis,follow_up_needed,senior_citizen
0,Dela Cruz,Male,San Roque,2026-01-05,34.0,65kg,165.0,120,36.5,Hypertension,Yes,0
2,Reyes,Male,San Roque,2026-01-07,NaN,58 kg,170.0,210,39.8,Hypertension,Yes,1
3,Bautista,Female,Poblacion,2026-01-08,27.0,70.2,NaN,130,36.7,Diabetes,No,0
5,Mendoza,Female,San Jose,2026-01-09,62.0,45.0kg,150.0,160,38.2,Flu,No,1
6,Torres,Male,Poblacion,2026-01-09,41.0,150,168.0,122,36.9,Hypertension,Yes,0
8,Aquino,Male,San Roque,2026-01-11,NaN,55.5,160.0,300,42.5,Diabetes Type 2,Yes,0
10,Delacruz,Female,Poblacion,2026-01-13,34.0,65kg,165.0,120,36.5,Hypertension,Yes,0
11,Santos,Male,San Jose,2026-01-13,5.0,18.5,110.0,95,37.0,Common Cold,No,0
12,Villanueva,Female,Sto Nino,2026-01-14,71.0,68,155.0,140,37.1,Migraine,No,1
13,Domingo,Male,San Roque,2026-01-15,45.0,75,180.0,135,36.4,Flu,Yes,0
16,Reyes,Female,San Roque,2026-01-17,55.0,90kg,158.0,150,40.1,Diabetes,Yes,1
17,Navarro,Male,San Jose,2026-01-18,NaN,52,NaN,127,36.7,Asthma,No,0
19,Pascual,Male,Poblacion,2026-01-20,38.0,77,162.0,131,36.9,Flu,Yes,0
20,Torres,Female,Sto. Nino,2026-01-20,41.0,68,168.0,122,36.5,Hypertension,Yes,0
21,Aquino,Male,San Roque,2026-01-21,NaN,58,173.0,128,37.2,Diabetes,No,1
22,Bautista,Female,San Jose,2026-01-22,60.0,95,5.9,145,39.0,Migraine,Yes,1
23,Cruz,Male,Bagumbayan,2026-01-23,34.0,65kg,165.0,120,36.5,Hypertension,Yes,0
24,Mercado,Female,Poblacion,2026-01-24,47.0,61,159.0,133,36.6,Uti,No,0
1,Santos,Female,Bagumbayan,NaT,5.0,18.5,110.0,95,37.0,Common Cold,No,0
4,Garcia,Male,Bagumbayan,NaT,NaN,80,175.0,118,36.6,Common Cold,Yes,1
7,Ramos,Female,Sto. Nino,NaT,8.0,20,128.0,100,36.8,Asthma,No,0
9,Fernandez,Female,Bagumbayan,NaT,29.0,62,172.0,125,36.5,Common Cold,No,0
14,Castro,Female,Bagumbayan,NaT,19.0,NaN,140.0,108,36.9,Uti,No,0

Total valid patients: 23
Average age: 36.39
Most common diagnosis: Hypertension
Percentage needing follow-up: 52.17 %

STEP 7

In [ ]:

duplicates = df[
    df.duplicated(
        subset=['patient_name', 'age', 'barangay'],
        keep=False
    )
]

display(duplicates[
    ['patient_name', 'age', 'barangay', 'visit_date']
])

   patient_name  age   barangay visit_date
8        Aquino  NaN  San Roque 2026-01-11
21       Aquino  NaN  San Roque 2026-01-21

STEP 8

In [ ]:

df['sex'] = df['sex'].str.strip().str.lower()

df['sex'] = df['sex'].replace({
    'm': 'Male',
    'male': 'Male',
    'f': 'Female',
    'female': 'Female'
})

print(df['sex'].unique())

['Male' 'Female']

STEP 9

In [ ]:

df['diagnosis'] = df['diagnosis'].str.strip().str.title()

df['diagnosis'] = df['diagnosis'].replace({
    'Migrain': 'Migraine'
})

print(df['diagnosis'].value_counts())

diagnosis
Hypertension       7
Common Cold        5
Flu                3
Diabetes           3
Asthma             2
Migraine           2
Uti                2
Diabetes Type 2    1
Name: count, dtype: int64

10. Which single data quality issue in this dataset do you think would cause the most harm if left unfixed in a real health center’s reporting system? Explain the real-world consequence.

The most harmful issue is incorrect vital signs because they can lead to wrong diagnosis or treatment.